### ISSUE TITLE
Tome Rater Project Review

### ISSUE THREAD

**Issue by wwang99** [Kondemonium/pwp-capstones#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_  4 (Exceeds Expectations) 
* _Comment(s):_
 
No errors!

### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations) 
* _Comment(s):_
 
- Nice job accounting for division by 0 errors if there are no ratings for a user or book!
- You went way beyond the project requirements with all this extra functionality, amazing job!

### Criteria 3: Software Architecture
* _Score Level:_ 3 (Meets Expectations) 
* _Comment(s):_
 
- Excellent job with writing the class/function specifications out in comments! This is a very good coding practice to have, it makes it very clear what everything does!
- Design wise, something like
```
    def valid_email(self, email):
        """Method to validate email address"""
        if "@" in email and email[-4::] in self.allowed_ends:
                    return True
        return False
```
belongs in the User class because it is something specific to a property only the User class has and so should be checked there before constructing a new User. TomeRater should just handle adding/creating a new user to its list of users rather than validating the creation of a new user.
- ``most_read_book`` doesn't need a parameter at all! When being called it should automatically be looking at self.books already, when creating functions be careful to think about which parameters are necessary and which are not! Same with ``most_expensive_book``

### Criteria 4: Uses Python Language Features
* _Score Level:_ 3 (Meets Expectations) 
* _Comment(s):_
 
- When you do stuff like this:
```
        if self.name == other_user.name and self.email == other_user.email:
            return True
        else:
            return False
```
 it's cleaner and more readable to just write ``return self.name == other_user.name and self.email == other_user.email``
- Similarly, with code like ``if self.unique_isbn(isbn) == True:``, doing == True is redundant and less readable since if ``self.unique_isbn(isbn)`` evaluates to True, the if statement becomes ``if True`` and will pass
- For your functions ``get_n_most_[blank]`` your algorithm works! However I think a cleaner way to do it would to just use sorted function to sort users/books dictionaries in descending order by their corresponding values then from that sorted array return only the first n entries!

### Overall Score: 14/16

Really well done project, wow! Your code is very well documented with comments and you added a lot of extra functionality! I can tell you have gotten quite proficient with Python, be proud of what you've learned!

**Comment by Kondemonium** [comment]
Thx for the feedback! In my case  `most_read_book` and `most_expensive_book` need parameters when my  `get_n_most` methods are looping them with parameters.
